baseURL = 'https://valurinpride.github.io/'
languageCode = 'en-us'
title = 'Tech Tracker'
theme = "blist-hugo-theme"
contentDir = "content"
# weight = 1
# DefaultContentLanguage = "en"
# DefaultContentLanguageInSubdir = false

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]
  # Custom copyright - optional
  copyright = "Copyright © 2023 - Mark Evans · All rights reserved"
  favicon = "favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  introTitle = "Valour In Pride"
  introSubtitle = "Akhand Bharat"
  introPhoto = "logo_black.jpg"

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  logo = "logo_black.jpg"
[[menu.main]]
  name = "Blog" 
  url = "/blog"
  weight = 1
[[menu.main]]
  name = "About" 
  url = "/about"
  weight = 2
